### ISSUE TITLE
Just the DM or each player?

### ISSUE THREAD

**Issue by YenBenGrey** [rm2kdev/foundry-dnd-beyond-rolls-module#1]
Hi, this is intriguing. Does each player need to follow the instructions or just the DM/GM?
Does it work if you’re using an online server?

**Comment by Jonwh25** [comment]
So I just played around with this and it looks like you have to setup the server.js file and node.js on every players own computer who wants to roll from ddb.  I thought I could install this on my foundry server and it didn't work.  So I connected to my foundry server and then on my local pc, it seemed to connect, but I think it is still buggy.

Mine kept trying to connect to the DDB server and dropping.

The doc is actually linking to the ddb-beyond gamelog settings wiki.  ha. I'm sticking with that for now.

**Comment by rm2kdev** [comment]
Haha yes I did link there haven’t had time to write some documentation for those steps and they are the same really 😛 

regarding your questions only the dm should have to run this, and only as campaign owner in ddv.

from there all rolls from all players in that campaign will be put in the game chat log on foundry where other tools like 3D dice rollers can pick it up and display them.

As for reconnections, it should only connect once every two hours but if it’s reconnecting all the time then it’s possible one of the values in settings is wrong (cobalt, game id, user id) and your getting kicked off the ddb servers.

Currenlty this early days of development and I’ve not implemented very robust error handling yet so everything has to be right for it to function right but I will improve it over time 😄

**Comment by YenBenGrey** [comment]
Thank you.
