### ISSUE TITLE
I am not a computer person.  How do you do any of this please?

### ISSUE THREAD

**Issue by YenBenGrey** [rm2kdev/foundry-dnd-beyond-rolls-module#3]
Hello, 

I have downloaded the Node thing and in the link for the companion app, I have no idea where to go to download it or what it looks like. Please can you help. Feels like I have fallen at the fist hurdle. 

I use a Mac OS Ventura.

**Comment by YenBenGrey** [comment]
I really really want to buy you a beer Man :-)

**Comment by rm2kdev** [comment]
I'll get some better instructions up when its out of beta :) but to help you out now try this.

- Press CMD + Space (to open spotlight up)
- Type Terminal and press enter
  - In Terminal
    - Type cd, then press space
    - drag the companion folder onto the terminal window
    - press enter
    - now type node server.js and press enter, you should see "Waiting for foundry connections"

The companion app is now running 😄, start foundry, install the module, follow the instructions to configure the module settings and enable it.

**Comment by Cybsjan** [comment]
Hi! 

On Windows machines install node.js

Then open up the command prompt by pressing the windows key and type cmd 
In that command prompt window, type: node and press space. Then drag in the server.js file and hit enter. Then you should see "Waiting for foundry connections"

**Comment by rm2kdev** [comment]
"now type node server.js and press enter" double check that previous message there's a step missing in what you've written here :)
