### ISSUE TITLE
Error getting cobalt socket token

### ISSUE THREAD

**Issue by Geektasticdad** [rm2kdev/foundry-dnd-beyond-rolls-module#5]
I've run into an issue with the foundry-dnd-beyond-rolls-module. I'm running it on the same Ubuntu server as Foundry VTT, it's Ubuntu 21.04.1 LTS

I get the foundry-dnd-beyond-rolls-companion running on the default port 8745 with no problem
![RemoteDesktopManager_dO2iZQWL5J](https://user-images.githubusercontent.com/73676044/210677681-2af8940c-5afa-46bf-8147-d178ed10b966.png)

However when I try to connect the module I get the following error:
![chrome_wHEKNHod1B](https://user-images.githubusercontent.com/73676044/210677789-8c9d3db0-0cde-475c-86b9-62c946ea6d61.png)

I can, however, hit the companion app on a lynx browser running on the same Ubuntu server: 
![RemoteDesktopManager_iJhP7Z7yf7](https://user-images.githubusercontent.com/73676044/210677943-c8f66e3b-d8d7-4e17-8751-df24c9c7b4fd.png)

and I can confirm it's hitting the companion app:
![BDAJDrEglc](https://user-images.githubusercontent.com/73676044/210678048-4fe60cdf-fb37-4868-b5aa-3e92e0be190c.png)

I have all the info requested including the Cobalt Cookie (which I use in a different module just fine)
![sIfrLVQ1me](https://user-images.githubusercontent.com/73676044/210678325-236d43e7-8ba9-4f6b-8b27-d6b31a295e93.png)

I disabled ufw as well, just in case it might have been the firewall. I have tried multiple iterations of changing the host in the server.js file from the private IP to 0.0.0.0. When I do change the host in the server.js file I can hit that IP and port with a 3rd party browser. I've run a traceroute from within the Ubuntu server and there are no hops in between (so I know it's not a routing issue). 

I was wondering if you have any suggestions.

**Comment by KrapfalAT** [comment]
I had the same Issue.
Fixed it with a workaround:
I entered my Cobalt Cookie Header directly in the server.js from the companion app.
![image](https://user-images.githubusercontent.com/19220141/225142022-6f1f83f0-0bb4-4399-8069-dbc08ed587b9.png)
