### ISSUE TITLE
missing server.js file

### ISSUE THREAD

**Issue by mtargonski** [rm2kdev/foundry-dnd-beyond-rolls-module#7]
Hi,
I have installed Node.js, tried running node server.js as mentioned, but node still errors out that there is no such file, and well I cannot blame it, as there is no such file in this repo. 

(tried running npm run build, no sucess)

How to run this app?

**Comment by rm2kdev** [comment]
The server.js file is in the companion app, not in the module.
check the first step of install instructions please :)
